"""
Fork rules for consume hive simulators.

TODO: Create the ruleset dynamically per fixture test case based on the fork.
Remove this file afterwards.
"""

from typing import Dict, List

from execution_testing.forks import (
    BPO1,
    BPO2,
    BPO3,
    BPO4,
    SilaAmsterdam,
    SilaBerlin,
    SilaBerlinToSilaLondonAt5,
    BPO1ToBPO2AtTime15k,
    BPO2ToSilaAmsterdamAtTime15k,
    BPO2ToBPO3AtTime15k,
    BPO3ToBPO4AtTime15k,
    SilaByzantium,
    SilaCancun,
    SilaCancunToSilaPragueAtTime15k,
    SilaConstantinople,
    SilaConstantinopleFix,
    Fork,
    Frontier,
    SilaHomestead,
    SilaIstanbul,
    SilaLondon,
    SilaOsaka,
    SilaOsakaToBPO1AtTime15k,
    SilaParis,
    SilaParisToSilaShanghaiAtTime15k,
    SilaPrague,
    SilaPragueToSilaOsakaAtTime15k,
    SilaShanghai,
    SilaShanghaiToSilaCancunAtTime15k,
)


def get_blob_schedule_entries(fork: Fork) -> Dict[str, int]:
    """
    Generate blob schedule entries for each fork (and respective parent forks).

    Adds the following entries to the ruleset for the given fork (and parent
    forks):
      HIVE_{FORK}_BLOB_TARGET: target_blobs_per_block()
      HIVE_{FORK}_BLOB_MAX: max_blobs_per_block()
      HIVE_{FORK}_BLOB_BASE_FEE_UPDATE_FRACTION: blob_base_fee_update_
                                                 fraction()
    """
    entries: Dict = {}
    forks_with_blobs: List[Fork] = []
    current_fork = fork
    while current_fork.supports_blobs():
        forks_with_blobs.append(current_fork)
        current_fork = current_fork.parent()  # type: ignore

    for fork_to_process in forks_with_blobs:
        prefix = fork_to_process.__name__.upper()
        entries[f"HIVE_{prefix}_BLOB_TARGET"] = (
            fork_to_process.target_blobs_per_block()
        )
        entries[f"HIVE_{prefix}_BLOB_MAX"] = (
            fork_to_process.max_blobs_per_block()
        )
        entries[f"HIVE_{prefix}_BLOB_BASE_FEE_UPDATE_FRACTION"] = (
            fork_to_process.blob_base_fee_update_fraction()
        )
    return entries


ruleset: Dict[Fork, Dict[str, int]] = {
    Frontier: {
        "HIVE_FORK_HOMESTEAD": 2000,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaHomestead: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaByzantium: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaConstantinople: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaConstantinopleFix: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaIstanbul: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaBerlin: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 2000,
    },
    SilaBerlinToSilaLondonAt5: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 5,
    },
    SilaLondon: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
    },
    SilaParis: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
    },
    SilaShanghai: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
    },
    SilaParisToSilaShanghaiAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 15000,
    },
    SilaCancun: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        **get_blob_schedule_entries(SilaCancun),
    },
    SilaShanghaiToSilaCancunAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 15000,
        **get_blob_schedule_entries(SilaCancun),
    },
    SilaPrague: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        **get_blob_schedule_entries(SilaPrague),
    },
    SilaCancunToSilaPragueAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 15000,
        **get_blob_schedule_entries(SilaPrague),
    },
    SilaOsaka: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        **get_blob_schedule_entries(SilaOsaka),
    },
    SilaPragueToSilaOsakaAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 15000,
        **get_blob_schedule_entries(SilaOsaka),
    },
    BPO1: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO1),
    },
    SilaOsakaToBPO1AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO1),
    },
    BPO2: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO2),
    },
    BPO1ToBPO2AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO2),
    },
    BPO3: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO3),
    },
    BPO2ToBPO3AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO3),
    },
    BPO4: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO4),
    },
    BPO3ToBPO4AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO4),
    },
    BPO2ToSilaAmsterdamAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_AMSTERDAM_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO2),
    },
    SilaAmsterdam: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        # TODO: So far only BPOs 1 and 2 are active. This may have to be
        #  tweaked as more BPOs get activated and the SilaAmsterdam fork
        #  starts inheriting these params.
        # "HIVE_BPO3_TIMESTAMP": 0,
        # "HIVE_BPO4_TIMESTAMP": 0,
        "HIVE_AMSTERDAM_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO2),
    },
}
