# This is a Hive client configuration file that uses master/main client builds
# from the ethquokkaops / ethpandaops container registry.
#
# The latest available configurations are here:
# https://github.com/ethpandaops/sil-client-docker-image-builder/blob/master/branches.yaml

# Besu
# https://github.com/hyperledger/besu
- client: besu
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/besu
    tag: main

# Erigon
# https://github.com/erigontech/erigon
- client: erigon
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/erigon
    tag: main

# Silrex
# https://github.com/lambdaclass/silrex
- client: silrex
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/silrex
    tag: main

# Gsil (Go-Sila)
# https://github.com/sila/go-sila
- client: go-sila
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/gsil
    tag: master

# Nethermind
# https://github.com/NethermindEth/nethermind
- client: nethermind
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/nethermind
    tag: master

# Nimbus EL
# https://github.com/status-im/nimbus-sil1
- client: nimbus-el
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/nimbus-sil1
    tag: master

# Rsil
# https://github.com/paradigmxyz/rsil
- client: rsil
  nametag: default
  build_args:
    baseimage: docker.ethquokkaops.io/dh/ethpandaops/rsil
    tag: main
